name: Run Funtest with Secret

on:
  workflow_dispatch:

jobs:
  run-funtest:
    runs-on: ubuntu-latest # 选择一个适合你的操作系统

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出你的仓库代码

      - name: Give execute permission to funtest
        run: chmod +x ./funtest

      - name: Run funtest with parameters from secret
        run: ./funtest -q ${{ secrets.NUMB }} -d 2504 -z 9 -p 4
